[package]
name = "mtsyntax-plus"
version = "0.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
trace = ["peg/trace"]

[dependencies]
peg = "0.8.5"
unicode-ident = "1.0"
