use std::{
    env::args,
    io::{self, stdin, stdout, Read, Write},
    process::exit,
};
use mtsyntax_plus::{build, parser, BuildContext, Error, OutputContext};

fn main() -> io::Result<()> {
    let count = args().count();
    if count != 1 {
        eprintln!("Error: Invalid args count {count}, expected 1 args\n");
        eprintln!("将MT管理器语法进行强化, 使其正则定义可以携带颜色");
        eprintln!("input from stdin, output to stdout");
        eprintln!("version: {}", env!("CARGO_PKG_VERSION"));
        exit(2);
    }

    let mut input = String::new();
    stdin().read_to_string(&mut input)?;

    let (begin, rules, end) = match parser::script(&input) {
        Ok(x) => x,
        Err(e) => {
            eprintln!("ParseError: at {}:{},",
                e.location.line,
                e.location.column,
            );
            eprintln!("expected {}", e.expected);
            exit(3)
        },
    };

    let mut out = stdout().lock();

    let indent = begin
        .rsplit_once(|ch| ! matches!(ch, ' ' | '\t'))
        .map_or("    ", |(_, ind)| ind);

    write!(&mut out, "{begin}// Generated by mtsyntax-plus begin\n{indent}")?;

    let mut ctx = BuildContext::default();
    let mut octx =
        OutputContext::new(|args| {
            write!(&mut out, "{args}")
        });

    if let Some(' ') | None = indent.chars().next() {
        octx.indent_level = indent.len() as u32 / 4;
        octx.indent_str = "    ";
    } else {
        octx.indent_str = "\t";
        octx.indent_level = indent.len() as u32;
    }

    if let Err(e) = build(rules, &mut octx, &mut ctx) {
        println!();
        match e {
            Error::UndefineRef(name) => {
                eprintln!("BuildError: undefine reference `{name}`");
            },
            Error::RepeatDefineName(name) => {
                eprintln!("BuildError: repeat define name `{name}`");
            },
            Error::RefNotARegexp(name) => {
                eprintln!("BuildError: reference `{name}` is not a regexp define");
            },
            Error::IOError(e) => Err(e)?,
        }
        exit(3)
    }

    write!(&mut out, "// Generated by mtsyntax-plus end\n{end}")?;

    Ok(())
}
